#!/bin/bash

# Autostart applications on *nix hosts using the init daemon.

### BEGIN INIT INFO
# Provides: deadline-pulse
# Required-Start: $network $syslog $sudo
# Required-Stop: $network $syslog $sudo
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start Deadline's Launcher application at boot time
# Description: Thinkbox Software's init support for Deadline Launcher
### END INIT INFO


INSTALL_DIR="/usr/local/Thinkbox/Deadline/"
LOGFILE="/var/log/deadline-launcher.log"

APP_PATH=$INSTALL_DIR/bin/deadlinelauncher	# `deadlinelauncher` is a wrapper script for starting DeadlineLauncher.exe
APP_NAME="Deadline Launcher"

USER="nobody"

touch $PIDFILE

start(){
	if [ -x $APP_PATH ]; then
		echo "Starting $APP_NAME on `date`" >> $LOGFILE
		
		# Run the app, logging all of its output to the specified file
		su -l $USER -c "nohup $APP_PATH -nogui" >> $LOGFILE 2>&1 < /dev/null & 
		echo "$APP_NAME Started"
		exit 0
	else
		echo "Could not find $APP_NAME"
		exit 2
	fi
}

stop(){
	echo "Attempting to stop $APP_NAME."
	# `su` is needed because we store the comm port number in the home folder
	su $USER -c "$APP_PATH -s"
	echo "Note that the slave may still be running."
	echo "Stopped $APP_NAME on `date`" >> $LOGFILE
	exit 0
}

# See how we were called.
case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

